import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const outDir = resolve(root, 'docs/gallery');
mkdirSync(outDir, { recursive: true });

const { render } = await import(resolve(root, 'dist/index.js'));

const gallery = [
  {
    slug: 'ai-adoption',
    config: {
      chart: 'line',
      size: 'share',
      palette: 'clarity',
      data: [
        { year: 2018, share: 3 },
        { year: 2019, share: 5 },
        { year: 2020, share: 9 },
        { year: 2021, share: 14 },
        { year: 2022, share: 23 },
        { year: 2023, share: 42 },
        { year: 2024, share: 61 },
        { year: 2025, share: 74 },
      ],
      x: 'year',
      y: 'share',
      title: 'Generative AI has gone from niche to mainstream',
      subtitle: 'Share of U.S. knowledge workers using generative AI tools at work, percent',
      source: 'McKinsey Global Survey on AI, 2025',
      xFormat: 'year',
      interpolation: 'curved',
      areaFill: true,
      showSymbols: 'last',
      showValueLabels: 'last',
    },
  },
  {
    slug: 'world-internet',
    config: {
      chart: 'geo',
      size: 'share',
      palette: 'viridis',
      basemap: 'world',
      code: 'code',
      value: 'usage',
      data: [
        { code: 'USA', usage: 92 },
        { code: 'CAN', usage: 94 },
        { code: 'MEX', usage: 76 },
        { code: 'BRA', usage: 81 },
        { code: 'ARG', usage: 87 },
        { code: 'CHL', usage: 89 },
        { code: 'COL', usage: 76 },
        { code: 'PER', usage: 71 },
        { code: 'VEN', usage: 62 },
        { code: 'GBR', usage: 97 },
        { code: 'FRA', usage: 92 },
        { code: 'DEU', usage: 93 },
        { code: 'ESP', usage: 94 },
        { code: 'ITA', usage: 87 },
        { code: 'NLD', usage: 97 },
        { code: 'BEL', usage: 94 },
        { code: 'CHE', usage: 96 },
        { code: 'AUT', usage: 93 },
        { code: 'SWE', usage: 98 },
        { code: 'NOR', usage: 99 },
        { code: 'FIN', usage: 98 },
        { code: 'DNK', usage: 99 },
        { code: 'ISL', usage: 99 },
        { code: 'POL', usage: 88 },
        { code: 'CZE', usage: 92 },
        { code: 'HUN', usage: 89 },
        { code: 'ROU', usage: 83 },
        { code: 'BGR', usage: 78 },
        { code: 'GRC', usage: 84 },
        { code: 'TUR', usage: 82 },
        { code: 'UKR', usage: 60 },
        { code: 'RUS', usage: 85 },
        { code: 'CHN', usage: 78 },
        { code: 'JPN', usage: 93 },
        { code: 'KOR', usage: 97 },
        { code: 'IND', usage: 52 },
        { code: 'IDN', usage: 66 },
        { code: 'VNM', usage: 79 },
        { code: 'THA', usage: 88 },
        { code: 'MYS', usage: 97 },
        { code: 'PHL', usage: 74 },
        { code: 'SGP', usage: 96 },
        { code: 'AUS', usage: 97 },
        { code: 'NZL', usage: 96 },
        { code: 'ARE', usage: 100 },
        { code: 'SAU', usage: 99 },
        { code: 'ISR', usage: 91 },
        { code: 'IRN', usage: 78 },
        { code: 'PAK', usage: 34 },
        { code: 'BGD', usage: 39 },
        { code: 'ZAF', usage: 77 },
        { code: 'NGA', usage: 55 },
        { code: 'KEN', usage: 42 },
        { code: 'EGY', usage: 72 },
        { code: 'ETH', usage: 19 },
        { code: 'TZA', usage: 22 },
        { code: 'UGA', usage: 10 },
        { code: 'MAR', usage: 88 },
        { code: 'DZA', usage: 71 },
        { code: 'TUN', usage: 79 },
        { code: 'GHA', usage: 68 },
        { code: 'SEN', usage: 58 },
        { code: 'AGO', usage: 36 },
        { code: 'COD', usage: 23 },
        { code: 'MOZ', usage: 17 },
      ],
      title: 'The world online',
      subtitle: 'Share of population with internet access, 2024 (percent)',
      source: 'International Telecommunication Union',
    },
  },
  {
    slug: 'energy-mix',
    config: {
      chart: 'stacked-area',
      size: 'share',
      palette: 'earth',
      data: [
        { year: 2000, coal: 39, gas: 19, oil: 2, nuclear: 19, hydro: 16, renewables: 5 },
        { year: 2005, coal: 41, gas: 20, oil: 2, nuclear: 16, hydro: 16, renewables: 5 },
        { year: 2010, coal: 40, gas: 22, oil: 3, nuclear: 13, hydro: 16, renewables: 6 },
        { year: 2015, coal: 38, gas: 23, oil: 3, nuclear: 11, hydro: 16, renewables: 9 },
        { year: 2018, coal: 37, gas: 23, oil: 2, nuclear: 10, hydro: 16, renewables: 12 },
        { year: 2020, coal: 34, gas: 24, oil: 2, nuclear: 10, hydro: 17, renewables: 13 },
        { year: 2022, coal: 35, gas: 22, oil: 2, nuclear: 9, hydro: 15, renewables: 17 },
        { year: 2024, coal: 33, gas: 22, oil: 2, nuclear: 9, hydro: 14, renewables: 20 },
      ],
      x: 'year',
      y: ['coal', 'gas', 'oil', 'nuclear', 'hydro', 'renewables'],
      title: 'The slow retreat of coal',
      subtitle: 'Global electricity generation by source, share of total (percent)',
      source: 'Ember Climate',
      xFormat: 'year',
      interpolation: 'linear',
    },
  },
  {
    slug: 'ev-sales',
    config: {
      chart: 'bar',
      size: 'share',
      palette: 'vibrant',
      data: [
        { country: 'Norway', share: 88.9 },
        { country: 'Iceland', share: 71.0 },
        { country: 'Sweden', share: 60.4 },
        { country: 'Denmark', share: 51.5 },
        { country: 'China', share: 47.0 },
        { country: 'Finland', share: 41.8 },
        { country: 'Netherlands', share: 34.7 },
        { country: 'Germany', share: 18.4 },
        { country: 'United Kingdom', share: 16.5 },
        { country: 'France', share: 15.7 },
        { country: 'United States', share: 9.3 },
        { country: 'Japan', share: 3.5 },
      ],
      x: 'country',
      y: 'share',
      orientation: 'horizontal',
      sort: 'desc',
      title: 'Norway is almost done with gasoline',
      subtitle: 'Electric vehicles as share of new passenger car sales, 2024 (percent)',
      source: 'International Energy Agency',
      showValueLabels: true,
    },
  },
  {
    slug: 'startup-funding',
    config: {
      chart: 'combo',
      size: 'share',
      palette: 'boardroom',
      data: [
        { quarter: '2022 Q1', raised: 162, median: 8.4 },
        { quarter: '2022 Q2', raised: 131, median: 7.2 },
        { quarter: '2022 Q3', raised: 89, median: 6.1 },
        { quarter: '2022 Q4', raised: 68, median: 5.2 },
        { quarter: '2023 Q1', raised: 76, median: 4.6 },
        { quarter: '2023 Q2', raised: 67, median: 4.3 },
        { quarter: '2023 Q3', raised: 74, median: 4.0 },
        { quarter: '2023 Q4', raised: 72, median: 4.1 },
        { quarter: '2024 Q1', raised: 94, median: 4.5 },
        { quarter: '2024 Q2', raised: 102, median: 5.0 },
        { quarter: '2024 Q3', raised: 88, median: 5.4 },
        { quarter: '2024 Q4', raised: 114, median: 6.2 },
      ],
      x: 'quarter',
      bars: 'raised',
      lines: 'median',
      title: 'Dollars rebound, median check size still low',
      subtitle: 'Global VC: total raised ($B, bars) vs. median round size ($M, line)',
      source: 'Crunchbase, CB Insights',
      interpolation: 'curved',
    },
  },
  {
    slug: 'central-bank-rates',
    config: {
      chart: 'line',
      size: 'share',
      palette: 'editorial',
      data: [
        { date: '2020-01', fed: 1.75, ecb: 0, boe: 0.75 },
        { date: '2020-06', fed: 0.25, ecb: 0, boe: 0.1 },
        { date: '2021-01', fed: 0.25, ecb: 0, boe: 0.1 },
        { date: '2021-12', fed: 0.25, ecb: 0, boe: 0.25 },
        { date: '2022-06', fed: 1.75, ecb: 0, boe: 1.25 },
        { date: '2022-12', fed: 4.5, ecb: 2.5, boe: 3.5 },
        { date: '2023-06', fed: 5.25, ecb: 4.0, boe: 5.0 },
        { date: '2023-12', fed: 5.5, ecb: 4.5, boe: 5.25 },
        { date: '2024-06', fed: 5.5, ecb: 4.25, boe: 5.25 },
        { date: '2024-12', fed: 4.5, ecb: 3.0, boe: 4.75 },
        { date: '2025-03', fed: 4.25, ecb: 2.5, boe: 4.5 },
      ],
      x: 'date',
      y: ['fed', 'ecb', 'boe'],
      title: 'The rate-hiking cycle, in three central banks',
      subtitle: 'Policy rate (percent) — U.S. Federal Reserve, European Central Bank, Bank of England',
      source: 'Fed, ECB, BoE',
      interpolation: 'stepped',
      lineWidth: 2.5,
    },
  },
  {
    slug: 'europe-gdp-growth',
    config: {
      chart: 'geo',
      size: 'share',
      palette: 'diverging-sunset',
      basemap: 'europe',
      code: 'code',
      value: 'growth',
      scale: 'diverging',
      data: [
        { code: 'IRL', growth: 4.8 },
        { code: 'ISL', growth: 3.5 },
        { code: 'MLT', growth: 4.1 },
        { code: 'POL', growth: 2.9 },
        { code: 'ESP', growth: 2.5 },
        { code: 'PRT', growth: 2.2 },
        { code: 'GRC', growth: 2.1 },
        { code: 'CYP', growth: 2.6 },
        { code: 'CZE', growth: 1.1 },
        { code: 'HUN', growth: 0.8 },
        { code: 'SVK', growth: 1.6 },
        { code: 'SVN', growth: 1.7 },
        { code: 'HRV', growth: 2.9 },
        { code: 'ROU', growth: 1.9 },
        { code: 'BGR', growth: 2.3 },
        { code: 'FRA', growth: 1.1 },
        { code: 'ITA', growth: 0.7 },
        { code: 'BEL', growth: 1.0 },
        { code: 'LUX', growth: 1.2 },
        { code: 'CHE', growth: 1.3 },
        { code: 'NLD', growth: 0.6 },
        { code: 'GBR', growth: 0.9 },
        { code: 'DEU', growth: -0.2 },
        { code: 'AUT', growth: -0.5 },
        { code: 'FIN', growth: -0.8 },
        { code: 'SWE', growth: 0.3 },
        { code: 'NOR', growth: 0.5 },
        { code: 'DNK', growth: 2.1 },
        { code: 'EST', growth: -0.9 },
        { code: 'LVA', growth: -0.4 },
        { code: 'LTU', growth: 2.1 },
        { code: 'UKR', growth: -1.8 },
        { code: 'BLR', growth: 2.2 },
        { code: 'RUS', growth: 3.2 },
        { code: 'TUR', growth: 3.1 },
        { code: 'ALB', growth: 3.4 },
        { code: 'BIH', growth: 2.2 },
        { code: 'SRB', growth: 3.0 },
        { code: 'MKD', growth: 2.1 },
        { code: 'MNE', growth: 3.2 },
        { code: 'MDA', growth: 0.1 },
      ],
      title: 'Growth returns to the periphery',
      subtitle: 'Real GDP growth across Europe, 2024 (percent)',
      source: 'Eurostat, IMF',
    },
  },
  {
    slug: 'spotify-streams',
    config: {
      chart: 'grouped-bar',
      size: 'share',
      palette: 'twilight',
      data: [
        { year: '2021', pop: 42, rock: 18, hiphop: 28, electronic: 12 },
        { year: '2022', pop: 40, rock: 16, hiphop: 32, electronic: 12 },
        { year: '2023', pop: 38, rock: 14, hiphop: 36, electronic: 12 },
        { year: '2024', pop: 36, rock: 13, hiphop: 39, electronic: 12 },
      ],
      x: 'year',
      y: ['pop', 'rock', 'hiphop', 'electronic'],
      title: 'Hip-hop overtakes pop on Spotify',
      subtitle: 'Share of total streams by genre, global (percent)',
      source: 'Spotify Wrapped, Luminate',
    },
  },
  {
    slug: 'usa-unemployment',
    config: {
      chart: 'geo',
      size: 'share',
      palette: 'mono-blue',
      basemap: 'usa-states',
      code: 'code',
      value: 'rate',
      data: [
        { code: 'AL', rate: 3.1 },
        { code: 'AK', rate: 4.6 },
        { code: 'AZ', rate: 3.8 },
        { code: 'AR', rate: 3.4 },
        { code: 'CA', rate: 5.3 },
        { code: 'CO', rate: 3.9 },
        { code: 'CT', rate: 4.1 },
        { code: 'DE', rate: 4.0 },
        { code: 'FL', rate: 3.2 },
        { code: 'GA', rate: 3.4 },
        { code: 'HI', rate: 3.0 },
        { code: 'ID', rate: 3.2 },
        { code: 'IL', rate: 4.8 },
        { code: 'IN', rate: 3.7 },
        { code: 'IA', rate: 2.9 },
        { code: 'KS', rate: 3.3 },
        { code: 'KY', rate: 4.6 },
        { code: 'LA', rate: 4.1 },
        { code: 'ME', rate: 3.4 },
        { code: 'MD', rate: 2.9 },
        { code: 'MA', rate: 3.7 },
        { code: 'MI', rate: 4.4 },
        { code: 'MN', rate: 3.0 },
        { code: 'MS', rate: 3.6 },
        { code: 'MO', rate: 3.6 },
        { code: 'MT', rate: 3.3 },
        { code: 'NE', rate: 2.8 },
        { code: 'NV', rate: 5.7 },
        { code: 'NH', rate: 2.7 },
        { code: 'NJ', rate: 4.7 },
        { code: 'NM', rate: 4.1 },
        { code: 'NY', rate: 4.2 },
        { code: 'NC', rate: 3.5 },
        { code: 'ND', rate: 2.2 },
        { code: 'OH', rate: 3.9 },
        { code: 'OK', rate: 3.3 },
        { code: 'OR', rate: 4.2 },
        { code: 'PA', rate: 3.5 },
        { code: 'RI', rate: 4.1 },
        { code: 'SC', rate: 3.7 },
        { code: 'SD', rate: 2.1 },
        { code: 'TN', rate: 3.2 },
        { code: 'TX', rate: 4.0 },
        { code: 'UT', rate: 3.0 },
        { code: 'VT', rate: 2.5 },
        { code: 'VA', rate: 2.9 },
        { code: 'WA', rate: 4.6 },
        { code: 'WV', rate: 4.2 },
        { code: 'WI', rate: 3.0 },
        { code: 'WY', rate: 3.3 },
      ],
      title: 'Where jobs are scarce, and where they aren’t',
      subtitle: 'U.S. unemployment rate by state, February 2025 (percent)',
      source: 'Bureau of Labor Statistics',
    },
  },
  {
    slug: 'smartphone-adoption',
    config: {
      chart: 'stacked-area',
      size: 'share',
      palette: 'clarity',
      data: [
        { year: 2010, ios: 16, android: 23, blackberry: 19, symbian: 37, other: 5 },
        { year: 2011, ios: 19, android: 37, blackberry: 13, symbian: 22, other: 9 },
        { year: 2012, ios: 20, android: 55, blackberry: 5, symbian: 4, other: 16 },
        { year: 2013, ios: 16, android: 74, blackberry: 2, symbian: 1, other: 7 },
        { year: 2014, ios: 15, android: 80, blackberry: 1, symbian: 0, other: 4 },
        { year: 2016, ios: 16, android: 82, blackberry: 0, symbian: 0, other: 2 },
        { year: 2018, ios: 19, android: 80, blackberry: 0, symbian: 0, other: 1 },
        { year: 2020, ios: 24, android: 75, blackberry: 0, symbian: 0, other: 1 },
        { year: 2022, ios: 27, android: 72, blackberry: 0, symbian: 0, other: 1 },
        { year: 2024, ios: 28, android: 71, blackberry: 0, symbian: 0, other: 1 },
      ],
      x: 'year',
      y: ['symbian', 'blackberry', 'other', 'ios', 'android'],
      title: 'The mobile OS wars, settled',
      subtitle: 'Global smartphone shipment share',
      source: 'IDC, Gartner',
      xFormat: 'year',
      interpolation: 'linear',
      normalize: true,
    },
  },
  {
    slug: 'cloud-market',
    config: {
      chart: 'donut',
      size: 'share',
      palette: 'carbon',
      data: [
        { provider: 'AWS', revenue: 107.6 },
        { provider: 'Microsoft Azure', revenue: 86.4 },
        { provider: 'Google Cloud', revenue: 43.2 },
        { provider: 'Alibaba Cloud', revenue: 13.5 },
        { provider: 'Oracle Cloud', revenue: 10.7 },
        { provider: 'IBM Cloud', revenue: 8.9 },
        { provider: 'Salesforce', revenue: 7.1 },
      ],
      label: 'provider',
      value: 'revenue',
      title: 'Three hyperscalers, the long tail',
      subtitle: 'Cloud infrastructure revenue by provider, 2024 ($B)',
      source: 'Synergy Research Group',
      centerValue: 'sum',
      centerLabel: '$B total',
      innerRadius: 'medium',
    },
  },
  {
    slug: 'saas-pricing',
    config: {
      chart: 'bar-split',
      size: 'share',
      palette: 'vibrant',
      data: [
        { tier: 'Free', notion: 0, slack: 0, linear: 0, figma: 0 },
        { tier: 'Starter', notion: 10, slack: 7.25, linear: 8, figma: 12 },
        { tier: 'Business', notion: 18, slack: 12.5, linear: 14, figma: 45 },
        { tier: 'Enterprise', notion: 25, slack: 19, linear: 24, figma: 75 },
      ],
      x: 'tier',
      y: ['notion', 'slack', 'linear', 'figma'],
      columns: 2,
      sharedScale: true,
      title: 'Productivity SaaS pricing, compared',
      subtitle: 'Monthly price per seat at each tier, USD',
      source: 'Public pricing pages, 2024',
      yFormat: 'currency',
    },
  },
  {
    slug: 'housing-affordability',
    config: {
      chart: 'line',
      size: 'share',
      palette: 'editorial',
      data: [
        { year: 2000, ratio: 3.4 },
        { year: 2002, ratio: 3.7 },
        { year: 2004, ratio: 4.1 },
        { year: 2006, ratio: 4.6 },
        { year: 2008, ratio: 4.5 },
        { year: 2010, ratio: 4.3 },
        { year: 2012, ratio: 4.2 },
        { year: 2014, ratio: 4.5 },
        { year: 2016, ratio: 4.8 },
        { year: 2018, ratio: 5.2 },
        { year: 2020, ratio: 5.6 },
        { year: 2022, ratio: 6.8 },
        { year: 2023, ratio: 7.1 },
        { year: 2024, ratio: 7.4 },
      ],
      x: 'year',
      y: 'ratio',
      title: 'A house now costs 7.4 years of median income',
      subtitle: 'Ratio of median U.S. home price to median household income',
      source: 'Federal Reserve, U.S. Census Bureau',
      xFormat: 'year',
      interpolation: 'curved',
      areaFill: true,
      showSymbols: 'last',
      showValueLabels: 'last',
    },
  },
  {
    slug: 'olympic-medals',
    config: {
      chart: 'stacked-bar',
      size: 'share',
      palette: 'boardroom',
      data: [
        { country: 'United States', gold: 40, silver: 44, bronze: 42 },
        { country: 'China', gold: 40, silver: 27, bronze: 24 },
        { country: 'Japan', gold: 20, silver: 12, bronze: 13 },
        { country: 'Australia', gold: 18, silver: 19, bronze: 16 },
        { country: 'France', gold: 16, silver: 26, bronze: 22 },
        { country: 'Netherlands', gold: 15, silver: 7, bronze: 12 },
        { country: 'Great Britain', gold: 14, silver: 22, bronze: 29 },
        { country: 'South Korea', gold: 13, silver: 9, bronze: 10 },
        { country: 'Italy', gold: 12, silver: 13, bronze: 15 },
        { country: 'Germany', gold: 12, silver: 13, bronze: 8 },
      ],
      x: 'country',
      y: ['gold', 'silver', 'bronze'],
      orientation: 'horizontal',
      title: 'Paris 2024: medal table, top 10',
      subtitle: 'Gold, silver and bronze medals by country',
      source: 'International Olympic Committee',
      showTotals: true,
    },
  },
  {
    slug: 'stock-indices',
    config: {
      chart: 'line',
      size: 'share',
      palette: 'twilight',
      data: [
        { date: '2020-01', sp500: 100, nasdaq: 100, dowjones: 100 },
        { date: '2020-04', sp500: 85, nasdaq: 96, dowjones: 80 },
        { date: '2020-08', sp500: 108, nasdaq: 128, dowjones: 100 },
        { date: '2020-12', sp500: 117, nasdaq: 147, dowjones: 110 },
        { date: '2021-06', sp500: 135, nasdaq: 166, dowjones: 125 },
        { date: '2021-12', sp500: 150, nasdaq: 180, dowjones: 135 },
        { date: '2022-06', sp500: 127, nasdaq: 140, dowjones: 122 },
        { date: '2022-12', sp500: 128, nasdaq: 132, dowjones: 128 },
        { date: '2023-06', sp500: 144, nasdaq: 170, dowjones: 133 },
        { date: '2023-12', sp500: 162, nasdaq: 195, dowjones: 148 },
        { date: '2024-06', sp500: 184, nasdaq: 220, dowjones: 156 },
        { date: '2024-12', sp500: 198, nasdaq: 242, dowjones: 170 },
      ],
      x: 'date',
      y: ['sp500', 'nasdaq', 'dowjones'],
      title: 'Five years, three indexes, one bull market',
      subtitle: 'Total return, January 2020 = 100',
      source: 'Yahoo Finance',
      interpolation: 'curved',
      lineWidth: 2.5,
    },
  },
  {
    slug: 'inflation-split',
    config: {
      chart: 'line-split',
      size: 'share',
      palette: 'editorial',
      data: [
        { year: 2020.0, usa: 2.5, eurozone: 1.4, uk: 1.8, japan: 0.7 },
        { year: 2020.5, usa: 1.0, eurozone: 0.4, uk: 1.0, japan: 0.3 },
        { year: 2021.0, usa: 1.4, eurozone: 0.9, uk: 0.7, japan: -0.6 },
        { year: 2021.5, usa: 5.4, eurozone: 2.2, uk: 2.0, japan: -0.3 },
        { year: 2022.0, usa: 7.5, eurozone: 5.1, uk: 5.5, japan: 0.5 },
        { year: 2022.5, usa: 9.1, eurozone: 8.6, uk: 9.4, japan: 2.4 },
        { year: 2023.0, usa: 6.5, eurozone: 9.2, uk: 10.5, japan: 4.0 },
        { year: 2023.5, usa: 3.0, eurozone: 5.5, uk: 7.9, japan: 3.3 },
        { year: 2024.0, usa: 3.4, eurozone: 2.9, uk: 4.0, japan: 2.6 },
        { year: 2024.5, usa: 3.0, eurozone: 2.5, uk: 2.0, japan: 2.8 },
        { year: 2025.0, usa: 2.9, eurozone: 2.4, uk: 2.5, japan: 3.6 },
      ],
      x: 'year',
      y: ['usa', 'eurozone', 'uk', 'japan'],
      columns: 2,
      sharedScale: true,
      title: 'The inflation wave, four economies',
      subtitle: 'Year-over-year consumer price inflation (percent)',
      source: 'OECD, central banks',
      xFormat: 'year',
      interpolation: 'curved',
    },
  },
  {
    slug: 'temperature-anomaly',
    config: {
      chart: 'bar',
      size: 'share',
      palette: 'diverging-sunset',
      data: [
        { year: 1980, anomaly: 0.27 },
        { year: 1985, anomaly: 0.14 },
        { year: 1990, anomaly: 0.45 },
        { year: 1995, anomaly: 0.48 },
        { year: 2000, anomaly: 0.42 },
        { year: 2005, anomaly: 0.68 },
        { year: 2010, anomaly: 0.72 },
        { year: 2012, anomaly: 0.65 },
        { year: 2014, anomaly: 0.75 },
        { year: 2016, anomaly: 1.01 },
        { year: 2018, anomaly: 0.85 },
        { year: 2019, anomaly: 0.98 },
        { year: 2020, anomaly: 1.01 },
        { year: 2021, anomaly: 0.85 },
        { year: 2022, anomaly: 0.89 },
        { year: 2023, anomaly: 1.17 },
        { year: 2024, anomaly: 1.28 },
      ],
      x: 'year',
      y: 'anomaly',
      title: 'Each of the last ten years was the hottest on record',
      subtitle: 'Global temperature anomaly relative to 1951-1980 average, Celsius',
      source: 'NASA GISS',
      xFormat: 'year',
      sort: 'none',
    },
  },
  {
    slug: 'streaming-market',
    config: {
      chart: 'pie',
      size: 'share',
      palette: 'vibrant',
      data: [
        { service: 'Netflix', share: 21.8 },
        { service: 'Prime Video', share: 19.4 },
        { service: 'Disney+', share: 11.3 },
        { service: 'Max', share: 8.7 },
        { service: 'Apple TV+', share: 6.2 },
        { service: 'Paramount+', share: 5.8 },
        { service: 'Hulu', share: 5.2 },
        { service: 'Peacock', share: 3.9 },
        { service: 'YouTube Premium', share: 3.1 },
        { service: 'Smaller services', share: 14.6 },
      ],
      label: 'service',
      value: 'share',
      title: 'A crowded streaming market',
      subtitle: 'U.S. subscription video-on-demand households, share of market',
      source: 'Parks Associates, Q4 2024',
      labelPlacement: 'outside',
      sort: 'desc',
      otherThreshold: 0,
    },
  },
  {
    slug: 'ai-model-costs',
    config: {
      chart: 'line',
      size: 'share',
      palette: 'carbon',
      data: [
        { year: 2020, cost: 180 },
        { year: 2021, cost: 60 },
        { year: 2022, cost: 20 },
        { year: 2023, cost: 5.5 },
        { year: 2024, cost: 0.9 },
        { year: 2025, cost: 0.14 },
      ],
      x: 'year',
      y: 'cost',
      title: 'The collapse in the cost of a million tokens',
      subtitle: 'Price to run GPT-3.5 quality inference, USD per million tokens',
      source: 'Epoch AI, vendor pricing',
      xFormat: 'year',
      yFormat: 'currency',
      interpolation: 'curved',
      lineWidth: 2.5,
      showSymbols: 'all',
      showValueLabels: 'first-last',
    },
  },
  {
    slug: 'ipo-performance',
    config: {
      chart: 'bar',
      size: 'share',
      palette: 'mono-blue',
      data: [
        { company: 'Rivian', change: -89 },
        { company: 'Coupang', change: -76 },
        { company: 'Robinhood', change: -45 },
        { company: 'Coinbase', change: -28 },
        { company: 'DoorDash', change: 9 },
        { company: 'Airbnb', change: 35 },
        { company: 'Snowflake', change: 48 },
        { company: 'CrowdStrike', change: 142 },
        { company: 'Palantir', change: 368 },
      ],
      x: 'company',
      y: 'change',
      title: 'Picking winners is hard',
      subtitle: 'Total return since IPO for selected tech listings, percent',
      source: 'Yahoo Finance, through March 2025',
      sort: 'asc',
      orientation: 'horizontal',
      showValueLabels: true,
    },
  },
];

console.log(`Rendering ${gallery.length} charts to ${outDir}...`);

let i = 0;
for (const entry of gallery) {
  i++;
  const n = String(i).padStart(2, '0');
  const filename = `${n}-${entry.slug}.png`;
  const outPath = join(outDir, filename);
  try {
    const png = await render(entry.config, { format: 'png' });
    writeFileSync(outPath, Buffer.from(png));
    const kb = (png.length / 1024).toFixed(1);
    console.log(`[${n}] ${filename.padEnd(40)} ${kb.padStart(6)} KB  (${entry.config.chart}, ${entry.config.palette})`);
  } catch (err) {
    console.error(`[${n}] ${filename} FAILED:`, err.message);
  }
}

console.log('\nDone.');
